import { fetchApi } from './api';
import type {
  SignedUploadParamsDto,
  ConfirmImageUploadInput,
} from '@home-inventory/shared';

/**
 * Uploads an image directly to Cloudinary using signed upload parameters generated by the backend.
 *
 * SECURITY INVARIANT:
 * The Cloudinary API Secret remains strictly server-side.
 * The client only receives the pre-calculated signature, timestamp, and public API key.
 */
export async function uploadImageToCloudinary(
  file: File,
  folder?: string
): Promise<ConfirmImageUploadInput> {
  // 1. Request signed parameters from backend
  const signRes = await fetchApi<SignedUploadParamsDto>('/uploads/sign', {
    method: 'POST',
    body: JSON.stringify(folder ? { folder } : {}),
  });

  const { signature, timestamp, apiKey, cloudName, folder: uploadFolder } = signRes.data;

  // 2. Prepare direct multipart upload to Cloudinary
  const formData = new FormData();
  formData.append('file', file);
  formData.append('api_key', apiKey);
  formData.append('timestamp', timestamp.toString());
  formData.append('signature', signature);
  formData.append('folder', uploadFolder);

  const uploadUrl = `https://api.cloudinary.com/v1_1/${cloudName}/image/upload`;
  const response = await fetch(uploadUrl, {
    method: 'POST',
    body: formData,
  });

  if (!response.ok) {
    const errText = await response.text();
    console.error('Cloudinary upload failed:', errText);
    throw new Error('Failed to upload photo. Please check your connection and try again.');
  }

  const json = await response.json();

  return {
    cloudinaryPublicId: json.public_id,
    url: json.url,
    secureUrl: json.secure_url,
    width: json.width,
    height: json.height,
    format: json.format,
    bytes: json.bytes,
    kind: 'primary',
    isPrimary: true,
  };
}
